## Auto-generated by data-raw/build_package.R - do not edit by hand.

#' Confirmed Exoplanets
#'
#' One row per confirmed exoplanet from NASA's Exoplanet Archive Planetary
#' Systems Composite Parameters (\code{pscomppars}) table. Each row carries
#' the archive's best composite parameter values, with the planet's host
#' star properties already merged in. Column names have been simplified for
#' classroom use; the original NASA short name for each column is listed in
#' the \code{archive_name} field of the data dictionary
#' (\code{system.file("extdata", "data_dictionary_planets.csv", package = "exoplanetdata")}).
#'
#' @format A data frame with 6278 rows and 28 variables:
#' \describe{
#'   \item{planet_name}{(character) Planet name most commonly used in the literature.}
#'   \item{host_name}{(character) Stellar name most commonly used in the literature.}
#'   \item{n_stars}{(numeric) Number of gravitationally bound stars in the planetary system.}
#'   \item{n_planets}{(numeric) Number of confirmed planets in the planetary system.}
#'   \item{discovery_method}{(factor) Method by which the planet was first identified (e.g. Transit, Radial Velocity).}
#'   \item{discovery_year}{(integer) Year the planet was discovered.}
#'   \item{discovery_facility}{(character) Name of the facility making the discovery observations.}
#'   \item{orbital_period_days}{(numeric, days) Time the planet takes to complete one orbit around its host (system).}
#'   \item{semi_major_axis_au}{(numeric, au) Longest radius of the elliptic orbit; for microlensing/imaging detections, the projected sky-plane separation.}
#'   \item{eccentricity}{(numeric) Amount by which the orbit deviates from a perfect circle (0 = circular).}
#'   \item{inclination_deg}{(numeric, deg) Angle of the orbit plane relative to the plane perpendicular to Earth's line of sight.}
#'   \item{radius_earth}{(numeric, Earth radii) Planet radius measured in units of Earth's radius.}
#'   \item{radius_jupiter}{(numeric, Jupiter radii) Planet radius measured in units of Jupiter's radius.}
#'   \item{mass_earth}{(numeric, Earth masses) Best mass estimate (Mass, M*sin(i)/sin(i), or M*sin(i)) in Earth masses.}
#'   \item{mass_jupiter}{(numeric, Jupiter masses) Best mass estimate (Mass, M*sin(i)/sin(i), or M*sin(i)) in Jupiter masses.}
#'   \item{density_g_cm3}{(numeric, g/cm^3) Planet mass per unit volume.}
#'   \item{eq_temp_k}{(numeric, K) Equilibrium temperature assuming a black-body planet heated by its host star.}
#'   \item{insolation_earth}{(numeric, Earth flux) Stellar flux at the planet relative to Earth's solar flux.}
#'   \item{star_spec_type}{(character) Morgan-Keenan spectral classification of the host star.}
#'   \item{star_temp_k}{(numeric, K) Black-body temperature emitting the same total electromagnetic radiation as the star.}
#'   \item{star_radius_solar}{(numeric, Solar radii) Stellar radius in units of the Sun's radius.}
#'   \item{star_mass_solar}{(numeric, Solar masses) Stellar mass in units of the Sun's mass.}
#'   \item{star_metallicity_dex}{(numeric, dex) Metal content of the stellar photosphere relative to hydrogen.}
#'   \item{star_log_g}{(numeric, log10(cm/s^2)) Gravitational acceleration at the stellar surface (log10).}
#'   \item{star_age_gyr}{(numeric, Gyr) Age of the host star in billions of years.}
#'   \item{ra_deg}{(numeric, deg) Right ascension of the planetary system in decimal degrees.}
#'   \item{dec_deg}{(numeric, deg) Declination of the planetary system in decimal degrees.}
#'   \item{distance_pc}{(numeric, pc) Distance to the planetary system in parsecs.}
#' }
#' @source NASA Exoplanet Archive Planetary Systems columns documentation:
#'   \url{https://exoplanetarchive.ipac.caltech.edu/docs/API_PS_columns.html}.
#'   Retrieved via the \pkg{REXoplanets} package.
"planets"

#' Stellar Hosts (Reference-Level)
#'
#' Reference-level stellar parameter data from NASA's Exoplanet Archive
#' \code{stellarhosts} table. Unlike \code{\link{planets}}, this table
#' contains MANY rows per host star (one per published parameter solution),
#' so it is the right table for studying the spread of published values for a
#' single star but NOT for one-row-per-star analyses. For most introductory
#' analyses, the host star's "best" parameters are already merged into
#' \code{planets} - reach for \code{stars} only when you need uncertainties,
#' alternative solutions, or full photometry.
#'
#' Many columns follow a base + suffix convention:
#' \itemize{
#'   \item \code{<col>_upper_err}: upper (+) 1-sigma uncertainty on \code{<col>}
#'   \item \code{<col>_lower_err}: lower (-) 1-sigma uncertainty on \code{<col>}
#'   \item \code{<col>_limit_flag}: limit flag (1 = upper limit, -1 = lower limit, 0 = measured)
#' }
#'
#' @format A data frame with 47558 rows and 134 variables:
#' \describe{
#'   \item{host_name}{(character) Stellar name most commonly used in the literature.}
#'   \item{hd_id}{(character) Henry Draper Catalog identifier.}
#'   \item{hip_id}{(character) Hipparcos Catalog identifier.}
#'   \item{tic_id}{(character) TESS Input Catalog identifier.}
#'   \item{ra_deg}{(numeric, deg) Right ascension of the planetary system in decimal degrees.}
#'   \item{ra_sexagesimal}{(character) Right ascension in sexagesimal hh:mm:ss notation.}
#'   \item{dec_deg}{(numeric, deg) Declination of the planetary system in decimal degrees.}
#'   \item{dec_sexagesimal}{(character) Declination in sexagesimal dd:mm:ss notation.}
#'   \item{galactic_lon_deg}{(numeric, deg) Galactic longitude of the planetary system.}
#'   \item{galactic_lat_deg}{(numeric, deg) Galactic latitude of the planetary system.}
#'   \item{ecliptic_lon_deg}{(numeric, deg) Ecliptic longitude of the planetary system.}
#'   \item{ecliptic_lat_deg}{(numeric, deg) Ecliptic latitude of the planetary system.}
#'   \item{mag_i_cousins}{(logical, mag) Apparent brightness in the I (Cousins) band.}
#'   \item{mag_i_cousins_upper_err}{(logical, mag) Upper (positive) 1-sigma uncertainty on sy_icmag.}
#'   \item{mag_i_cousins_lower_err}{(logical, mag) Lower (negative) 1-sigma uncertainty on sy_icmag.}
#'   \item{temperature_k}{(numeric, K) Black-body temperature emitting the same total electromagnetic radiation as the star.}
#'   \item{temperature_k_upper_err}{(numeric, K) Upper (positive) 1-sigma uncertainty on st_teff.}
#'   \item{temperature_k_lower_err}{(numeric, K) Lower (negative) 1-sigma uncertainty on st_teff.}
#'   \item{temperature_k_limit_flag}{(numeric) Limit flag for st_teff: 1 = upper limit, -1 = lower limit, 0 = a measured value.}
#'   \item{metallicity_dex}{(numeric, dex) Metal content of the stellar photosphere relative to hydrogen.}
#'   \item{metallicity_dex_upper_err}{(numeric, dex) Upper (positive) 1-sigma uncertainty on st_met.}
#'   \item{metallicity_dex_lower_err}{(numeric, dex) Lower (negative) 1-sigma uncertainty on st_met.}
#'   \item{metallicity_dex_limit_flag}{(numeric) Limit flag for st_met: 1 = upper limit, -1 = lower limit, 0 = a measured value.}
#'   \item{radial_velocity_km_s}{(numeric, km/s) Star's velocity along the line of sight from Earth.}
#'   \item{radial_velocity_km_s_upper_err}{(numeric, km/s) Upper (positive) 1-sigma uncertainty on st_radv.}
#'   \item{radial_velocity_km_s_lower_err}{(numeric, km/s) Lower (negative) 1-sigma uncertainty on st_radv.}
#'   \item{radial_velocity_km_s_limit_flag}{(numeric) Limit flag for st_radv: 1 = upper limit, -1 = lower limit, 0 = a measured value.}
#'   \item{v_sin_i_km_s}{(numeric, km/s) Equatorial rotational velocity multiplied by sin(inclination).}
#'   \item{v_sin_i_km_s_upper_err}{(numeric, km/s) Upper (positive) 1-sigma uncertainty on st_vsin.}
#'   \item{v_sin_i_km_s_lower_err}{(numeric, km/s) Lower (negative) 1-sigma uncertainty on st_vsin.}
#'   \item{v_sin_i_km_s_limit_flag}{(numeric) Limit flag for st_vsin: 1 = upper limit, -1 = lower limit, 0 = a measured value.}
#'   \item{luminosity_log_solar}{(numeric, log10(L_sun)) Energy emitted per unit time, in solar luminosities (log10).}
#'   \item{luminosity_log_solar_upper_err}{(numeric, log10(L_sun)) Upper (positive) 1-sigma uncertainty on st_lum.}
#'   \item{luminosity_log_solar_lower_err}{(numeric, log10(L_sun)) Lower (negative) 1-sigma uncertainty on st_lum.}
#'   \item{luminosity_log_solar_limit_flag}{(numeric) Limit flag for st_lum: 1 = upper limit, -1 = lower limit, 0 = a measured value.}
#'   \item{log_g}{(numeric, log10(cm/s^2)) Gravitational acceleration at the stellar surface (log10).}
#'   \item{log_g_upper_err}{(numeric, log10(cm/s^2)) Upper (positive) 1-sigma uncertainty on st_logg.}
#'   \item{log_g_lower_err}{(numeric, log10(cm/s^2)) Lower (negative) 1-sigma uncertainty on st_logg.}
#'   \item{log_g_limit_flag}{(numeric) Limit flag for st_logg: 1 = upper limit, -1 = lower limit, 0 = a measured value.}
#'   \item{age_gyr}{(numeric, Gyr) Age of the host star in billions of years.}
#'   \item{age_gyr_upper_err}{(numeric, Gyr) Upper (positive) 1-sigma uncertainty on st_age.}
#'   \item{age_gyr_lower_err}{(numeric, Gyr) Lower (negative) 1-sigma uncertainty on st_age.}
#'   \item{age_gyr_limit_flag}{(numeric) Limit flag for st_age: 1 = upper limit, -1 = lower limit, 0 = a measured value.}
#'   \item{mass_solar}{(numeric, Solar masses) Stellar mass in units of the Sun's mass.}
#'   \item{mass_solar_upper_err}{(numeric, Solar masses) Upper (positive) 1-sigma uncertainty on st_mass.}
#'   \item{mass_solar_lower_err}{(numeric, Solar masses) Lower (negative) 1-sigma uncertainty on st_mass.}
#'   \item{mass_solar_limit_flag}{(numeric) Limit flag for st_mass: 1 = upper limit, -1 = lower limit, 0 = a measured value.}
#'   \item{density_g_cm3}{(numeric, g/cm^3) Stellar mass per unit volume.}
#'   \item{density_g_cm3_upper_err}{(numeric, g/cm^3) Upper (positive) 1-sigma uncertainty on st_dens.}
#'   \item{density_g_cm3_lower_err}{(numeric, g/cm^3) Lower (negative) 1-sigma uncertainty on st_dens.}
#'   \item{density_g_cm3_limit_flag}{(numeric) Limit flag for st_dens: 1 = upper limit, -1 = lower limit, 0 = a measured value.}
#'   \item{radius_solar}{(numeric, Solar radii) Stellar radius in units of the Sun's radius.}
#'   \item{radius_solar_upper_err}{(numeric, Solar radii) Upper (positive) 1-sigma uncertainty on st_rad.}
#'   \item{radius_solar_lower_err}{(numeric, Solar radii) Lower (negative) 1-sigma uncertainty on st_rad.}
#'   \item{radius_solar_limit_flag}{(numeric) Limit flag for st_rad: 1 = upper limit, -1 = lower limit, 0 = a measured value.}
#'   \item{n_stars}{(numeric) Number of gravitationally bound stars in the planetary system.}
#'   \item{n_planets}{(numeric) Number of confirmed planets in the planetary system.}
#'   \item{n_moons}{(numeric) Number of confirmed moons in the planetary system.}
#'   \item{proper_motion_total_mas_yr}{(numeric, mas/yr) Total angular change in position over time relative to Solar System barycenter.}
#'   \item{proper_motion_total_mas_yr_upper_err}{(numeric, mas/yr) Upper (positive) 1-sigma uncertainty on sy_pm.}
#'   \item{proper_motion_total_mas_yr_lower_err}{(numeric, mas/yr) Lower (negative) 1-sigma uncertainty on sy_pm.}
#'   \item{proper_motion_ra_mas_yr}{(numeric, mas/yr) Proper motion in right ascension.}
#'   \item{proper_motion_ra_mas_yr_upper_err}{(numeric, mas/yr) Upper (positive) 1-sigma uncertainty on sy_pmra.}
#'   \item{proper_motion_ra_mas_yr_lower_err}{(numeric, mas/yr) Lower (negative) 1-sigma uncertainty on sy_pmra.}
#'   \item{proper_motion_dec_mas_yr}{(numeric, mas/yr) Proper motion in declination.}
#'   \item{proper_motion_dec_mas_yr_upper_err}{(numeric, mas/yr) Upper (positive) 1-sigma uncertainty on sy_pmdec.}
#'   \item{proper_motion_dec_mas_yr_lower_err}{(numeric, mas/yr) Lower (negative) 1-sigma uncertainty on sy_pmdec.}
#'   \item{parallax_mas}{(numeric, mas) Annual parallax of the system.}
#'   \item{parallax_mas_upper_err}{(numeric, mas) Upper (positive) 1-sigma uncertainty on sy_plx.}
#'   \item{parallax_mas_lower_err}{(numeric, mas) Lower (negative) 1-sigma uncertainty on sy_plx.}
#'   \item{distance_pc}{(numeric, pc) Distance to the planetary system in parsecs.}
#'   \item{distance_pc_upper_err}{(numeric, pc) Upper (positive) 1-sigma uncertainty on sy_dist.}
#'   \item{distance_pc_lower_err}{(numeric, pc) Lower (negative) 1-sigma uncertainty on sy_dist.}
#'   \item{mag_b_johnson}{(numeric, mag) Apparent brightness in the B (Johnson) photometric band.}
#'   \item{mag_b_johnson_upper_err}{(numeric, mag) Upper (positive) 1-sigma uncertainty on sy_bmag.}
#'   \item{mag_b_johnson_lower_err}{(numeric, mag) Lower (negative) 1-sigma uncertainty on sy_bmag.}
#'   \item{mag_v_johnson}{(numeric, mag) Apparent brightness in the V (Johnson) photometric band.}
#'   \item{mag_v_johnson_upper_err}{(numeric, mag) Upper (positive) 1-sigma uncertainty on sy_vmag.}
#'   \item{mag_v_johnson_lower_err}{(numeric, mag) Lower (negative) 1-sigma uncertainty on sy_vmag.}
#'   \item{mag_j_2mass}{(numeric, mag) Apparent brightness in the 2MASS J band.}
#'   \item{mag_j_2mass_upper_err}{(numeric, mag) Upper (positive) 1-sigma uncertainty on sy_jmag.}
#'   \item{mag_j_2mass_lower_err}{(numeric, mag) Lower (negative) 1-sigma uncertainty on sy_jmag.}
#'   \item{mag_h_2mass}{(numeric, mag) Apparent brightness in the 2MASS H band.}
#'   \item{mag_h_2mass_upper_err}{(numeric, mag) Upper (positive) 1-sigma uncertainty on sy_hmag.}
#'   \item{mag_h_2mass_lower_err}{(numeric, mag) Lower (negative) 1-sigma uncertainty on sy_hmag.}
#'   \item{mag_k_2mass}{(numeric, mag) Apparent brightness in the 2MASS Ks band.}
#'   \item{mag_k_2mass_upper_err}{(numeric, mag) Upper (positive) 1-sigma uncertainty on sy_kmag.}
#'   \item{mag_k_2mass_lower_err}{(numeric, mag) Lower (negative) 1-sigma uncertainty on sy_kmag.}
#'   \item{mag_u_sloan}{(numeric, mag) Apparent brightness in the SDSS u band.}
#'   \item{mag_u_sloan_upper_err}{(numeric, mag) Upper (positive) 1-sigma uncertainty on sy_umag.}
#'   \item{mag_u_sloan_lower_err}{(numeric, mag) Lower (negative) 1-sigma uncertainty on sy_umag.}
#'   \item{mag_r_sloan}{(numeric, mag) Apparent brightness in the SDSS r band.}
#'   \item{mag_r_sloan_upper_err}{(numeric, mag) Upper (positive) 1-sigma uncertainty on sy_rmag.}
#'   \item{mag_r_sloan_lower_err}{(numeric, mag) Lower (negative) 1-sigma uncertainty on sy_rmag.}
#'   \item{mag_i_sloan}{(numeric, mag) Apparent brightness in the SDSS i band.}
#'   \item{mag_i_sloan_upper_err}{(numeric, mag) Upper (positive) 1-sigma uncertainty on sy_imag.}
#'   \item{mag_i_sloan_lower_err}{(numeric, mag) Lower (negative) 1-sigma uncertainty on sy_imag.}
#'   \item{mag_z_sloan}{(numeric, mag) Apparent brightness in the SDSS z band.}
#'   \item{mag_z_sloan_upper_err}{(numeric, mag) Upper (positive) 1-sigma uncertainty on sy_zmag.}
#'   \item{mag_z_sloan_lower_err}{(numeric, mag) Lower (negative) 1-sigma uncertainty on sy_zmag.}
#'   \item{mag_w1_wise}{(numeric, mag) Apparent brightness in the WISE 3.4 micron band.}
#'   \item{mag_w1_wise_upper_err}{(numeric, mag) Upper (positive) 1-sigma uncertainty on sy_w1mag.}
#'   \item{mag_w1_wise_lower_err}{(numeric, mag) Lower (negative) 1-sigma uncertainty on sy_w1mag.}
#'   \item{mag_w2_wise}{(numeric, mag) Apparent brightness in the WISE 4.6 micron band.}
#'   \item{mag_w2_wise_upper_err}{(numeric, mag) Upper (positive) 1-sigma uncertainty on sy_w2mag.}
#'   \item{mag_w2_wise_lower_err}{(numeric, mag) Lower (negative) 1-sigma uncertainty on sy_w2mag.}
#'   \item{mag_w3_wise}{(numeric, mag) Apparent brightness in the WISE 12 micron band.}
#'   \item{mag_w3_wise_upper_err}{(numeric, mag) Upper (positive) 1-sigma uncertainty on sy_w3mag.}
#'   \item{mag_w3_wise_lower_err}{(numeric, mag) Lower (negative) 1-sigma uncertainty on sy_w3mag.}
#'   \item{mag_w4_wise}{(numeric, mag) Apparent brightness in the WISE 22 micron band.}
#'   \item{mag_w4_wise_upper_err}{(numeric, mag) Upper (positive) 1-sigma uncertainty on sy_w4mag.}
#'   \item{mag_w4_wise_lower_err}{(numeric, mag) Lower (negative) 1-sigma uncertainty on sy_w4mag.}
#'   \item{mag_g_sloan}{(numeric, mag) Apparent brightness in the SDSS g band.}
#'   \item{mag_g_sloan_upper_err}{(numeric, mag) Upper (positive) 1-sigma uncertainty on sy_gmag.}
#'   \item{mag_g_sloan_lower_err}{(numeric, mag) Lower (negative) 1-sigma uncertainty on sy_gmag.}
#'   \item{mag_gaia}{(numeric, mag) Apparent brightness in the Gaia G band.}
#'   \item{mag_gaia_upper_err}{(numeric, mag) Upper (positive) 1-sigma uncertainty on sy_gaiamag.}
#'   \item{mag_gaia_lower_err}{(numeric, mag) Lower (negative) 1-sigma uncertainty on sy_gaiamag.}
#'   \item{mag_tess}{(numeric, mag) Apparent brightness in the TESS bandpass.}
#'   \item{mag_tess_upper_err}{(numeric, mag) Upper (positive) 1-sigma uncertainty on sy_tmag.}
#'   \item{mag_tess_lower_err}{(numeric, mag) Lower (negative) 1-sigma uncertainty on sy_tmag.}
#'   \item{system_name}{(character) Name of the system the star belongs to.}
#'   \item{metallicity_ratio}{(character) Ratio used to express metallicity (e.g. [Fe/H], [M/H]).}
#'   \item{spectral_type}{(character) Morgan-Keenan spectral classification of the star.}
#'   \item{mag_kepler}{(numeric, mag) Apparent brightness in the Kepler bandpass.}
#'   \item{mag_kepler_upper_err}{(logical, mag) Upper (positive) 1-sigma uncertainty on sy_kepmag.}
#'   \item{mag_kepler_lower_err}{(logical, mag) Lower (negative) 1-sigma uncertainty on sy_kepmag.}
#'   \item{rotation_period_days}{(numeric, days) Time required for one full rotation (assuming solid-body rotation).}
#'   \item{rotation_period_days_upper_err}{(numeric, days) Upper (positive) 1-sigma uncertainty on st_rotp.}
#'   \item{rotation_period_days_lower_err}{(numeric, days) Lower (negative) 1-sigma uncertainty on st_rotp.}
#'   \item{rotation_period_days_limit_flag}{(numeric) Limit flag for st_rotp: 1 = upper limit, -1 = lower limit, 0 = a measured value.}
#'   \item{gaia_dr2_id}{(character) Gaia Data Release 2 identifier.}
#'   \item{gaia_dr3_id}{(character) Gaia Data Release 3 identifier.}
#'   \item{circumbinary_flag}{(numeric) 1 if planet orbits a binary system, 0 otherwise.}
#' }
#' @source NASA Exoplanet Archive Stellar Hosts columns documentation:
#'   \url{https://exoplanetarchive.ipac.caltech.edu/docs/API_STELLARHOSTS_columns.html}.
#'   Retrieved via the \pkg{REXoplanets} package.
"stars"

